### PR TITLE
Update gds sso and govuk content models gems

### PR DESCRIPTION
**Pull request by Davidslv**
**Part of**: https://trello.com/c/RWkPMkJK/533-incident-investigation-why-does-panopticon-history-show-updates-from-unknown-user

I have upgraded [govuk_content_models](https://github.com/alphagov/govuk_content_models) which is now version [32.3.0](https://github.com/alphagov/govuk_content_models/commit/4669a53b725456c48cc2fb594ecb024c33385048).

I also had to update [gds-sso](https://github.com/alphagov/gds-sso) gem to `~> 11.2.1` since it is a dependency of `govuk_content_models` `32.2.0`

This is necessary for us to use `save_as_task` method, provided by `govuk_content_models` version `32.3.0`

### CODE REVIEW

**Comment by tijmenb** [comment]
I would wait with this PR until https://github.com/alphagov/govuk_content_models/pull/360 gets merged, so those changes can go in and you don't have to do a new PR for that.

**Comment by Davidslv** [comment]
I agree, I'm just preparing my work so it doesn't get forgotten.

**Comment by Davidslv** [comment]
Waiting for https://github.com/alphagov/govuk_content_models/pull/361

**Comment by Davidslv** [comment]
Updated last commit to use `govuk_content_models` `32.3.0`

**Comment by tijmenb** [comment]
A `mongoid` bump in this upgrade is somehow preventing deploys for this branch:

https://deploy.integration.publishing.service.gov.uk/job/Deploy_App/2039/console

**Pull request merged**
