### PR TITLE
🌟 Remove the JSON API 🌟

### PR DESCRIPTION
**Pull request by whoojemaflip**
Finally, the last app to consume Panopticon's JSON API has been updated.

This change removes two JSON methods:

GET /artefacts
PUT /artefact/:slug.json

### CODE REVIEW

**Comment by tijmenb** [comment]
AAAAAAAAAAAAHHHHHHHHHH I love this.

**Comment by h-lame** [comment]
How are we doing on that big "get rid of panopticon" diagram?  Does doing this mean we've crossed a cake line yet?

**Comment by whoojemaflip** [comment]
Between [this](https://github.com/alphagov/publisher/pull/534) and this, I think we've inadvertently crossed the line several times.

**Comment by davidbasalla** [comment]
🍰  it!!!

**Pull request merged**
